Linux builds

diff --git a/Jenkinsfile_Windows b/Jenkinsfile_Windows
--- a/Jenkinsfile_Windows
+++ b/Jenkinsfile_Windows
@@ -1,7 +1,5 @@
 pipeline {
-    agent {
-		lable 'Linux_bookstore'
-	}
+    agent any
     environment {
         MAVEN_OPTS = '-Xmx1024m'
     }
@@ -22,9 +20,11 @@ pipeline {
         stage('Build') {
             steps {
                 echo 'Build the project'
-                sh '''
-                    echo "Workspace: $pwd"
-                    ls -l
+                powershell '''
+                    Write-Host "Workspace: $PWD"
+                    Get-ChildItem
+                    if (-not (Test-Path "pom.xml")) { Write-Error "pom.xml not found"; exit 1 }
+                    Write-Host "JAVA_HOME=$env:JAVA_HOME"
                     java -version
                     mvn -version
                     mvn -B clean package
@@ -34,12 +34,15 @@ pipeline {
         stage ('Deployment') {
             steps {
                 echo 'Deploy the application'
-              sh '''
+              bat '''
                     echo "Deploying the application..."
-                    	cp -rf target/onlinebookstore.war /opt/tomcat/webapps/
-			ls -l /opt/tomcat/webapps/
-			sleep 10
-			
+                    # Add your deployment commands here
+                    copy /Y target\\onlinebookstore.war "C:\\Program Files\\Apache Software Foundation\\Tomcat 11.0\\webapps"
+			Dir "C:\\Program Files\\Apache Software Foundation\\Tomcat 11.0\\webapps\\"
+			timeout /t 30
+			Dir "C:\\Program Files\\Apache Software Foundation\\Tomcat 11.0\\webapps\\"
+			timeout /t 60
+			Dir "C:\\Program Files\\Apache Software Foundation\\Tomcat 11.0\\webapps\\"
                 '''
             }
         }
